-- Canonical article list for coverage & rank. Single source of truth.
-- article = chapter key (e.g. "110", "250"). UI shows all active articles.

CREATE TABLE IF NOT EXISTS public.articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article text NOT NULL UNIQUE,
  title text,
  sort_order int NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_articles_active_sort ON public.articles(active, sort_order) WHERE active = true;

ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read articles" ON public.articles
  FOR SELECT USING (true);

-- Seed common NEC chapters (idempotent)
INSERT INTO public.articles (article, title, sort_order, active)
VALUES
  ('110', 'Requirements for Electrical Installations', 10, true),
  ('250', 'Grounding and Bonding', 20, true),
  ('310', 'Conductors for General Wiring', 30, true),
  ('408', 'Switchboards and Panelboards', 40, true)
ON CONFLICT (article) DO NOTHING;
