-- Chapters table for grouping articles in Code Coverage UI
CREATE TABLE IF NOT EXISTS public.chapters (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapter_number int NOT NULL UNIQUE,
  title text NOT NULL,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_chapters_sort ON public.chapters(sort_order);

ALTER TABLE public.chapters ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read chapters" ON public.chapters FOR SELECT USING (true);

-- Add chapter_number to articles (nullable for backward compat)
ALTER TABLE public.articles ADD COLUMN IF NOT EXISTS chapter_number int;

-- Seed NEC chapter groupings
INSERT INTO public.chapters (chapter_number, title, sort_order)
VALUES
  (1, 'General', 10),
  (2, 'Wiring and Protection', 20),
  (3, 'Wiring Methods and Materials', 30),
  (4, 'Equipment for General Use', 40)
ON CONFLICT (chapter_number) DO NOTHING;

-- Map existing articles to chapters (110->1, 250->2, 310->3, 408->4)
UPDATE public.articles SET chapter_number = 1 WHERE article = '110' AND chapter_number IS NULL;
UPDATE public.articles SET chapter_number = 2 WHERE article = '250' AND chapter_number IS NULL;
UPDATE public.articles SET chapter_number = 3 WHERE article = '310' AND chapter_number IS NULL;
UPDATE public.articles SET chapter_number = 4 WHERE article = '408' AND chapter_number IS NULL;
